name: Scan Docker Image in GHCR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scan-docker-image:
    name: Trivy Scan Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      env:
        CR_PAT: ${{ secrets.GHCR_PAT }} # Personal Access Token with read:packages scope
      run: |
        echo "$CR_PAT" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Scan Docker Image with Trivy Action
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: "ghcr.io/ankitdit06/vulboard/vulboard:latest" # Replace with your image name
        format: "template" # Use Go template format for output
        template: "@trivy-format.tmpl" # Path to the Go template file
        output: "trivy_report.json"

    - name: Display CVE Report
      run: |
        echo "CVE Report:" && cat trivy_report.json

    - name: Upload CVE Report to API
      env:
        API_URL: ${{ secrets.API_URL }}
      run: |
          # Make a POST request with the CVE report
          curl -X POST -H "Content-Type: application/json" --data @trivy_report.json $API_URL

    - name: Confirm Upload
      run: echo "CVE report uploaded successfully to ${{ secrets.API_URL }}"
